{
 "title": "Keycloak events",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "realm",
    "query": "SHOW TAG VALUES from \"14d\".event WITH KEY = \"realmId\""
   },
   {
    "name": "eventType",
    "query": "SHOW TAG VALUES from event WITH KEY = \"type\" where \"realmId\" =~ /^$realm$/"
   },
   {
    "name": "adminEventType",
    "query": "SHOW TAG VALUES from adminEvent WITH KEY = \"type\" where \"realmId\" =~ /^$realm$/"
   }
  ]
 },
 "panels": [
  {
   "title": "$realm realm - Event count per type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "event",
     "select": [
      [
       { "params": [ "ipAddress" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "realmId", "operator": "=~", "value": "/^$realm$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$eventType$/" }
     ]
    }
   ]
  },
  {
   "title": "$realm realm - AdminEvent count per type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "adminEvent",
     "select": [
      [
       { "params": [ "ipAddress" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "realmId", "operator": "=~", "value": "/^$realm$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$adminEventType$/" }
     ]
    }
   ]
  },
  {
   "title": "Event Details",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "event",
     "select": [
      [
       { "params": [ "ipAddress" ], "type": "field" }
      ],
      [
       { "params": [ "userId" ], "type": "field" }
      ],
      [
       { "params": [ "username" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "details" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "realmId", "operator": "=~", "value": "/^$realm$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$eventType$/" }
     ]
    }
   ]
  },
  {
   "title": "AdminEvent Details",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "resourceType" ], "type": "tag" },
      { "params": [ "operationType" ], "type": "tag" }
     ],
     "measurement": "adminEvent",
     "query": "SELECT \"ipAddress\", \"userId\", \"error\", \"representation\", \"resourcePath\" FROM \"14d\".\"adminEvent\" WHERE $timeFilter GROUP BY \"resourceType\", \"operationType\" ORDER BY time DESC",
     "select": [
      [
       { "params": [ "ipAddress" ], "type": "field" }
      ],
      [
       { "params": [ "userId" ], "type": "field" }
      ],
      [
       { "params": [ "error" ], "type": "field" }
      ],
      [
       { "params": [ "representation" ], "type": "field" }
      ],
      [
       { "params": [ "resourcePath" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "realmId", "operator": "=~", "value": "/^$realm$/" },
      { "condition": "AND", "key": "type", "operator": "=~", "value": "/^$adminEventType$/" }
     ]
    }
   ]
  }
 ]
}